### ISSUE TITLE
Internet is lagging, we've got SSL error

### ISSUE THREAD

**Issue by Beetario** [dyvosvit/telegb#3]
What is the problem? thanks
```
nelson4215@instance-3:~/telegb$ sudo python telepl.py
Internet is lagging, we've got SSL error
Internet is lagging, we've got SSL error
Internet is lagging, we've got SSL error
Internet is lagging, we've got SSL error
Internet is lagging, we've got SSL error
Internet is lagging, we've got SSL error
```

**Comment by utdrmac** [comment]
@nelsonmurciia It means that Polo is down. That specific error happens when the SSL verification fails, probably due to CloudFlare returning "site is down" or other error message. You can ignore them and when Polo load lightens, the bot will resume normal operations.

**Comment by utdrmac** [comment]
@nelsonmurciia Please close if resolved

**Comment by Beetario** [comment]
Thanku, is found.
